services:
  db:
    image: mysql:5.7 #Se estiver em ARM mude para 8.0
    volumes:
      - wordpress_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Minhasenha2020 #Troque Pela Sua Senha
      MYSQL_DATABASE: wordpress #Troque Pela Sua Base de Dados
      MYSQL_USER: aulafabricando #Troque Pela Sua Usuário
      MYSQL_PASSWORD: kifndyalsh #Troque Pela Sua Senha

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_wp-content:/var/www/html/wp-content
      - wordpress_php:/usr/local/etc/php
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: aulafabricando #Troque Pela Sua Usuário
      WORDPRESS_DB_PASSWORD: kifndyalsh #Troque Pela Sua Senha
      WORDPRESS_DB_NAME: wordpress #Troque Pela Sua Base de Dados
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`wordpress.seusite.com.br`) || Host(`www.wordpress.seusite.com.br`)" # Troque pelo seu dominio ou subdominio
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls.certresolver=leresolver"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.wordpress-secure.rule=Host(`wordpress.seusite.com.br`) || Host(`www.wordpress.seusite.com.br`)" # Troque pelo seu dominio ou subdominio
      - "traefik.http.routers.wordpress-secure.entrypoints=web"
      - "traefik.http.routers.wordpress-secure.middlewares=redirect-to-https"

networks:
  default:
    name: wordpress_01
    external: true

volumes:
  wordpress_db_data:
  wordpress_wp-content:
  wordpress_php:
