version: '3.8'

services:
  db:
    image: mysql:5.7 #Se estiver em ARM mude para 8.0
    volumes:
      - wordpress_01_db_data:/var/lib/mysql #Troque o Numero Para Rodar Multiplos WP
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootsenha #Troque Pela Sua Senha
      MYSQL_DATABASE: wordpress #Troque Pela Sua Base de Dados
      MYSQL_USER: wordpress #Troque Pela Sua Usuário
      MYSQL_PASSWORD: wordpress #Troque Pela Sua Senha

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_01_wp-content:/var/www/html/wp-content #Troque o Numero Para Rodar Multiplos WP
      - wordpress_01_php:/usr/local/etc/php #Troque o Numero Para Rodar Multiplos WP
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress #Troque Pela Sua Usuário
      WORDPRESS_DB_PASSWORD: wordpress #Troque Pela Sua Senha
      WORDPRESS_DB_NAME: wordpress #Troque Pela Sua Base de Dados
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`wordpress01.seusite.com`)" #Troque Pela URL
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls.certresolver=leresolver"
      #Troque o Numero Para Rodar Multiplos WP EX: traefik.http.routers.wordpress02. Faca Isso Nas 3 Linhas

networks:
  default:
    name: wordpress_01
    external: true

volumes:
  wordpress_01_db_data:
  wordpress_01_wp-content:
  wordpress_01_php:
#Troque os Numeros Dos Volumes Para Rodar Multiplos Wordpress