version: "3.7"

services:
  postgrespgvector:
    image: astraonline/postgrespgvector:2024
    environment:
      - POSTGRES_PASSWORD=Mfcd62!!Mfcd62!!
    networks:
      - minha_rede
    ports:
      - 5436:5432
    volumes:
      - postgrespgvector:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M

volumes:
  postgrespgvector:
    external: true
    name: postgrespgvector

networks:
  minha_rede:
    name: minha_rede
    external: true

