x-logging: &default-logging
  options:
    max-size: "10m"
    max-file: "5"
  driver: json-file

services:
  dnsmasq:
    image: dockurr/dnsmasq
    container_name: dnsmasq
    logging: *default-logging
    networks:
      - dnsmasq_network
    volumes:
     - /var/lib/docker/volumes/dnsmasq_storage/_data/dnsmasq.conf:/etc/dnsmasq.conf
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: ['if [ -z "$$(netstat -nltu |grep \:53)" ]; then exit 1;else exit 0; fi']
      interval: 2s
      timeout: 2s
      retries: 20
    ports:
      - 53:53/udp
      - 53:53/tcp
    environment:
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
    deploy:
      mode: replicated
      replicas: 1
      placement:
         constraints: [ node.role == manager ]
      resources:
        limits:
          cpus: "0.55"
          memory: 220M

networks:
  dnsmasq_network:
    external: true

volumes:
  dnsmasq_storage:
    external: true

