version: '3.7'

##############
#
# Para migrar o banco do Woofed CRM, execute o comando abaixo no console do container Principal:
#
# rails db:migrate
#
# Acesso o Link e escolha sua Versão:
#
# https://hub.docker.com/r/douglara/woofedcrm/tags
#
#############

services:
  woofedcrm:
    image: douglara/woofedcrm:add-evolution_apis_controller-28cd38e5680fe9dce9110bd0e06f902105157d0c
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    networks:
      - minha_rede
    volumes:
      - woofedcrm_data:/app
    environment:
      - ENABLE_USER_SIGNUP=true
      - RAILS_ENV=production
      - RACK_ENV=production
      - NODE_ENV=production
      - MOTOR_AUTH_USERNAME=Seu Email
      - MOTOR_AUTH_PASSWORD=Sua Senha
      - FRONTEND_URL=https://seudominio.com.br
      - DATABASE_URL=postgres://postgres:Mfcd62!!Mfcd62!!@postgres:5432/woofedcrm
      - REDIS_URL=redis://redis:6379/0
      - ACTIVE_STORAGE_SERVICE=local
      - RAILS_LOG_LEVEL=debug
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.woofedcrm.rule=Host(`seudominio.com.br`)
        - traefik.http.routers.woofedcrm.entrypoints=websecure
        - traefik.http.routers.woofedcrm.tls.certresolver=letsencryptresolver
        - traefik.http.routers.woofedcrm.priority=1
        - traefik.http.routers.woofedcrm.service=woofedcrm
        - traefik.http.services.woofedcrm.loadbalancer.server.port=3000
        - traefik.http.services.woofedcrm.loadbalancer.passhostheader=true
        - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.routers.woofedcrm.middlewares=sslheader@docker

  sidekiq:
    image: douglara/woofedcrm:add-evolution_apis_controller-28cd38e5680fe9dce9110bd0e06f902105157d0c
    command: bundle exec sidekiq -C config/sidekiq.yml
    networks:
      - minha_rede
    volumes:
      - woofedcrm_data:/app
    environment:
      - ENABLE_USER_SIGNUP=true
      - RAILS_ENV=production
      - RACK_ENV=production
      - NODE_ENV=production
      - MOTOR_AUTH_USERNAME=Seu Email
      - MOTOR_AUTH_PASSWORD=Sua Senha
      - FRONTEND_URL=https://seudominio.com.br
      - DATABASE_URL=postgres://postgres:Mfcd62!!Mfcd62!!@postgres:5432/woofedcrm
      - REDIS_URL=redis://redis:6379/0
      - ACTIVE_STORAGE_SERVICE=local
      - RAILS_LOG_LEVEL=debug
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M

  good_job:
    image: douglara/woofedcrm:add-evolution_apis_controller-28cd38e5680fe9dce9110bd0e06f902105157d0c
    command: bundle exec good_job
    networks:
      - minha_rede
    volumes:
      - woofedcrm_data:/app
    environment:
      - ENABLE_USER_SIGNUP=true
      - RAILS_ENV=production
      - RACK_ENV=production
      - NODE_ENV=production
      - MOTOR_AUTH_USERNAME=Seu Email
      - MOTOR_AUTH_PASSWORD=Sua Senha
      - FRONTEND_URL=https://seudominio.com.br
      - DATABASE_URL=postgres://postgres:Mfcd62!!Mfcd62!!@postgres:5432/woofedcrm
      - REDIS_URL=redis://redis:6379/0
      - ACTIVE_STORAGE_SERVICE=local
      - RAILS_LOG_LEVEL=debug
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M

volumes:
  woofedcrm_data:
    external: true
    name: woofedcrm_data

networks:
  minha_rede:
    external: true
    name: minha_rede