services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    restart: unless-stopped
    networks:
      bplus_network:
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined #optional
    volumes:
      - /var/docker/calibre/config:/config
    environment:
      - TZ='America/Sao_Paulo'
      - PUID=1000
      - PGID=1000
    ports:
      - 8080:8080
      - 8181:8181
      - 8081:8081

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    hostname: calibre-web
    restart: unless-stopped
    networks:
      bplus_network:
    security_opt:
      - no-new-privileges:true
    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/docker/calibre-web/config:/config
      - /var/docker/calibre/config/library:/books
    environment:
      - TZ='America/Sao_Paulo'
      - PUID=1000
      - PGID=1000
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    depends_on:
      - calibre
    ports:
      - 8083:8083
    labels:
      - "traefik.enable=false"
      # HTTP Routers
      - "traefik.http.routers.calibre-web.entrypoints=websecure"
      - traefik.http.routers.adguard-rtr.rule=Host(`calibre.${DNS_DOMAIN}`) || Host(`www.calibre.${DNS_DOMAIN}`)
      # Middlewares
      # - "traefik.http.routers.calibre-web.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.calibre-web.service=calibre-web-svc"
      - "traefik.http.services.calibre-web-svc.loadbalancer.server.port=8083"
networks:
  bplus_network:
    name: bplus_network
    external: true
