services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    hostname: heimdall
    networks:
      - heimdall_network    
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ${PWD}/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    
networks:
  heimdall_network:
    name: heimdall_network
    external: true
