services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    hostname: heimdall
    security_opt:
      - no-new-privileges:true
    networks:
      - bplus_network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      # - ./config:/config
      - /var/docker/heimdall/config:/config
    ports:
      - 8085:80
      # - 443:443
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
      # HTTP Routers
      - "traefik.http.routers.heimdall.entrypoints=websecure"
      - "traefik.http.routers.heimdall.rule=Host(`heimdall.bplus.lab`) || Host(`www.heimdall.bplus.lab`)"
      # Middlewares
      # - "traefik.http.routers.homarr.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.heimdall.service=heimdall-svc"
      - "traefik.http.services.heimdall-svc.loadbalancer.server.port=8085"
networks:
  bplus_network:
    name: bplus_network
    external: true
