services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    hostname: homarr
    restart: unless-stopped
    environment:
      TZ: America/Sao_Paulo
      # NODE_TLS_REJECT_UNAUTHORIZED: 0
      BASE_URL: homarr.bplus.lab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /var/docker/homarr/configs:/app/data/configs
      - /var/docker/homarr/icons:/app/public/icons
      - /var/docker/homarr/data:/data
    ports:
      - '7575:7575'
    networks:
      - bplus_network
    labels:
      - "traefik.enable=false"
      # HTTP Routers
      - "traefik.http.routers.homarr.entrypoints=websecure"
      - traefik.http.routers.adguard-rtr.rule=Host(`homarr.${DNS_DOMAIN}`) || Host(`www.homarr.${DNS_DOMAIN}`)
      # Middlewares
      # - "traefik.http.routers.homarr.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.homarr.service=homarr-svc"
      - "traefik.http.services.homarr-svc.loadbalancer.server.port=7575"
networks:
  bplus_network:
    name: bplus_network
    external: true
