services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.bplus.lab

    restart: always
    networks:
      - bplus_network
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - /var/docker/dms/mail-data/:/var/mail/
      - /var/docker/dms/mail-state/:/var/mail-state/
      - /var/docker/dms/mail-logs/:/var/log/mail/
      - /var/docker/dms/config/:/tmp/docker-mailserver/
      # - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_RSPAMD=0
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=0
      - ENABLE_POSTGREY=0
      - ENABLE_SPAMASSASSIN=0
      # If letsencrypt for SSL/TLS certificate is used (otherwise adapt)
      - SSL_TYPE=letsencrypt
      - PERMIT_DOCKER=network
      - ONE_DIR=1
      - SPOOF_PROTECTION=0
      - TZ=America/Sao_Paulo
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

networks:
  bplus_network:
    name: bplus_network
    external: true
