services:
  noip:
    image: ghcr.io/noipcom/noip-duc:latest
    container_name: noip
    hostname: noip
    restart: unless-stopped

    networks:
      - bplus_network    
    environment:
      NOIP_USERNAME: xx
      NOIP_PASSWORD: xx
      NOIP_HOSTNAMES:  xx
      TZ: America/Sao_Paulo
      
networks:
  bplus_network:
    name: bplus_network
    external: true
