services:
  noip:
    image: ghcr.io/noipcom/noip-duc:latest
    container_name: noip
    hostname: noip
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true   
    networks:
      - bplus_network    
    environment:
      NOIP_USERNAME: xxx@xxxx
      NOIP_PASSWORD: xxxx
      NOIP_HOSTNAMES:  xxxx
      TZ: America/Sao_Paulo
      
networks:
  bplus_network:
    name: bplus_network
    external: true
