services:
 
  pgadmin:
    image: dpage/pgadmin4:8.10
    container_name: pgadmin
    hostname: pgadmin
    networks:
      - bplus_network
    user: '$UID:$GID'
    environment:
      - POSTGRES_PASSWORD=changeME
      - PGADMIN_DEFAULT_EMAIL=wborbajr@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=changeME
      # - PUID=1000
      # - PGID=1000
      - TZ=America/Sao_Paulo
    ports:
      - 15433:80
    volumes:
      - /var/docker/pgadmin/:/var/lib/pgadmin/:rw
    labels:
      - "traefik.enable=false"
      # HTTP Routers
      - "traefik.http.routers.pgadmin.entrypoints=websecure"
      - traefik.http.routers.adguard-rtr.rule=Host(`pgadmin.${DNS_DOMAIN}`) || Host(`www.pgadmin.${DNS_DOMAIN}`)
      # Middlewares
      # - "traefik.http.routers.pgadmin.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.pgadmin.service=pgadmin-svc"
      - "traefik.http.services.pgadmin-svc.loadbalancer.server.port=15433"
networks:
  bplus_network:
    name: bplus_network
    external: true
