services:
  pgsql:
    image: 'postgres:latest'
    container_name: pgsql
    hostname: pgsql
    security_opt:
      - no-new-privileges:true
    networks:
      - bplus_network
    environment:
      - POSTGRES_PASSWORD=changeME
      - PGADMIN_DEFAULT_EMAIL=wborbajr@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=changeME
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    ports:
      - 15432:5432
    volumes:
      - /var/docker/pgsql/db-data/:/var/lib/postgresql/data/
      # - /var/docker/pgsql/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    hostname: pgadmin
    security_opt:
      - no-new-privileges:true
    networks:
      - bplus_network
    environment:
      - POSTGRES_PASSWORD=changeME
      - PGADMIN_DEFAULT_EMAIL=wborbajr@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=changeME
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    ports:
      - 15433:80
    depends_on:
      - pgsql
    volumes:
      - /var/docker/pgadmin-data/:/var/lib/pgadmin/

networks:
  bplus_network:
    name: bplus_network
    external: true
    
#init.sql    
#-- create a table
#CREATE TABLE test(
#  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
#  name TEXT NOT NULL,
#  archived BOOLEAN NOT NULL DEFAULT FALSE
#);
#
#-- add test data
#INSERT INTO test (name, archived)
#  VALUES ('test row 1', true),
#  ('test row 2', false);    
  
