services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    ports:
      - "192.168.1.19:53:53/tcp"
      - "192.168.1.19:53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      # - "8282:82/tcp"
    environment:
      TZ: 'America/Sao_Paulo'
      PIHOLE_DNS_: 1.1.1.1;1.0.0.1
      WEB_PORT: 8282
      # WEBPASSWORD: 'xxxxxx'
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 1.0.0.1
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
      - './var-log/pihole.log:/var/log/pihole.log'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - bplus_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=Host(`pihole.bplus.lab`) || Host(`www.pihole.bplus.lab`)
      - traefik.http.services.pihole.loadbalancer.server.port=8282

      - traefik.http.middlewares.redirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.redirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.pihole.middlewares=redirect

volumes:
  pihole_storage:
    name: pihole_storage
    external: true    

networks:
  bplus_network:
    name: bplus_network
    external: true
