services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    restart: unless-stopped
    networks:
      - bplus_network
    security_opt:
      - no-new-privileges:true
    ports:
      - "192.168.1.19:53:53/tcp"
      - "192.168.1.19:53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "8282:82/tcp"
    environment:
      TZ: 'America/Sao_Paulo'
      PIHOLE_DNS_: 1.1.1.1;1.0.0.1
      WEB_PORT: 82
      # WEBPASSWORD: 'xxxxxx'
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 1.0.0.1
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
      - './var-log/pihole.log:/var/log/pihole.log'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    labels:
      - "traefik.enable=false"
      # HTTP Routers
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.whoami.rule=Host(`pihole.bplus.lab`) || Host(`www.pihole.bplus.lab`)"
      # Middlewares
      # - "traefik.http.routers.pihole.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.pihole.service=pihole-svc"
      - "traefik.http.services.pihole-svc.loadbalancer.server.port=8282"
      
networks:
  bplus_network:
    name: bplus_network
    external: true
