services:
  snappymail:
    image: djmaze/snappymail:latest
    container_name: snappymail
    hostname: snappymail

    environment:
      - TZ=America/Sao_Paulo
    networks:
      - bplus_network
    restart: unless-stopped
    volumes:
      - /var/docker/snappymail/data/:/snappymail/data/
    ports:
      - 8888:8888
      - 9000:9000
networks:
  bplus_network:
    name: bplus_network
    external: true
