services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: cavelab
    restart: unless-stopped

    networks:
      - bplus_network
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun
    environment:
      - TS_AUTHKEY=tskey-auth-kAigSAfEHg11CNTRL-vmKXPVY9YdbvnFAfAQeGdbDTyCQiXae7K # To use an auth key for an ephemeral node; Generate from your admin Dashboard
      - TS_ACCEPT_DNS=false # To opt out of Tailscale DNS
      - TS_EXTRA_ARGS=--advertise-exit-node # To allow setting of exit nodes
      - TS_HOSTNAME=cavelab # To set a unique machine name for the device
      - TS_STATE_DIR=/var/lib/tailscale # To make the machine maintain with the same IP and name
      - TS_SOCKET=/var/run/tailscale/tailscaled.sock # Specifying the /var/lib/tailscale/tailscaled.sock location allows use of standard Tailscale commands 
      # - TS_EXTRA_ARGS=--accept-routes # Add any other supported arguments in the docker commandline style: e.g. --advertise-exit-node
      # - TS_STATE_DIR=/var/lib/tailscale # Required to create a persistent container state that will survive reboots
      - TZ= America/Sao_Paulo
    volumes:
      # Mount volume from host system to container
      # [host system volume]:[container volume]:[permission]
      - "/var/docker/tailscale/config:/etc/tailscale" # Mount configurations folder
      - "/var/docker/tailscale/data:/var/lib/tailscale" # Mount applications data
      - "/dev/net/tun:/dev/net/tun" # Network

networks:
  bplus_network:
    name: bplus_network
    external: true
