services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: cavelab
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun
    volumes:
      - tailscale_storage:/var/lib/tailscale
    environment:
      TS_AUTHKEY: tskey-auth-kPEbohV8pc11CNTRL-rZa7tGAVWaaepakYXyT6aaVi7kvkh55T
      # TS_ROUTES: 192.168.1.9/32
      TS_EXTRA_ARGS: --accept-routes
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: 'false'
      TS_ACCEPT_DNS: 'false'
      TZ: America/Sao_Paulo
    # networks:
    #   br0:
        # ipv4_address: 192.168.1.5
    restart: unless-stopped
    networks:
      - bplus_network
    
volumes:
  tailscale_storage:
    external: true    

networks:
  bplus_network:
    name: bplus_network
    external: true
