services:
  watchtower:
    image: ghcr.io/containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    networks:
      bplus_network:
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: 'America/Sao_Paulo'
      WATCHTOWER_DEBUG: true
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_REMOVE_VOLUMES: true
      # DOCKER_AP_VERSION="1.40"
      WATCHTOWER_INCLUDE_STOPPED: true
      WATCHTOWER_MONITOR_ONLY: true
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: wborbajr@gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_TO: wborbajr@gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: smtp.gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: wborbajr@gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD:  '(AmandaTB00)'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  bplus_network:
    name: bplus_network
    external: true
