services:
  whoami:
    image: traefik/whoami:latest
    container_name: whoami
    hostname: whoami

    networks:
      - bplus_network
    ports:
     - "80:80"
    command:
      - "--verbose"
    labels:
      - "traefik.enable=false"
      # HTTP Routers
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.rule=Host(`whoami.bplus.lab`) || Host(`www.whoami.bplus.lab`)"
      # Middlewares
      # - "traefik.http.routers.whoami.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.whoami.service=whoami-svc"
      - "traefik.http.services.whoami-svc.loadbalancer.server.port=80"


networks:
  bplus_network:
    name: bplus_network
    external: true
