services:
  whoami:
    image: traefik/whoami:latest
    container_name: whoami
    hostname: whoami
    networks:
      - bplus_network
    command:
      - "--verbose"
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.bplus.lab`) || Host(`www.whoami.bplus.lab`)
      - traefik.http.services.whoami.loadbalancer.server.port=80

      - traefik.http.middlewares.redirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.redirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.whoami.middlewares=redirect
      
networks:
  bplus_network:
    name: bplus_network
    external: true
