services:
  whoami:
    image: traefik/whoami:latest
    container_name: whoami
    hostname: whoami

    networks:
      - bplus_network
    ports:
     - "7080:80"
    command:
      - "--verbose"
    labels:
      - "traefik.enable=false"
      # HTTP Routers
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - traefik.http.routers.adguard-rtr.rule=Host(`whoami.${DNS_DOMAIN}`) || Host(`www.whoami.${DNS_DOMAIN}`)
      # Middlewares
      # - "traefik.http.routers.whoami.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.whoami.service=whoami-svc"
      - "traefik.http.services.whoami-svc.loadbalancer.server.port=7080"


networks:
  bplus_network:
    name: bplus_network
    external: true
