services:
  n8n_editor:
    image: n8nio/n8n:next
    command: start
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    networks:
      - network_public
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n_queue
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=UltraSecretPassWord
      #
      - N8N_PORT=5678
      - N8N_HOST=n8n.bplus.intra
      - N8N_EDITOR_BASE_URL=https://n8n.bplus.intra/
      - N8N_PROTOCOL=https
      - N8N_ENDPOINT_WEBHOOK=webhook
      - N8N_ENCRYPTION_KEY=r3djGX2vPoeL9zKL
      - N8N_METRICS=false
      - N8N_PAYLOAD_SIZE_MAX=16
      - N8N_LOG_LEVEL=info      
      - N8N_VERSION_NOTIFICATION_ENABLED=true
      - N8N_PUBLIC_API_SWAGGERUI_DISABLED=true
      - N8N_TEMPLATES_ENABLE=true
      - N8N_ONBOARDING_FLOW_DISABLED=false
      - N8N_WORKFLOW_TAGS_DISABLED=false
      - N8N_HIDE_USAGE_PAGE=true
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_REINSTALL_MISSING_PACKAGES=true  
      #
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336
      - EXECUTIONS_DATA_PRUNE_HARD_DELETE_INTERVAL=15
      - EXECUTIONS_DATA_PRUNE_SOFT_DELETE_INTERVAL=60
      - EXECUTIONS_DATA_PRUNE_MAX_COUNT=10000
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=none
      - EXECUTIONS_DATA_SAVE_ON_PROGRESS=true
      - EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=true
      #
      - NODE_ENV=production
      - WEBHOOK_URL=https://webhook.seudominio.com.br/
      #
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=3
      #
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_FUNCTION_ALLOW_EXTERNAL=moment,lodash
      #
      - EXECUTION_TIMEOUT=3600
      - EXECUTION_TIMEOUT_MAX=7200     
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336
      #
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
      
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: 
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
      update_config:
      	parallelism: 1
      	delay: 30s
      	order: start-first
      	failure_action: rollback        
      	  
       labels:
         - traefik.enable=true
         - traefik.http.routers.n8n_editor.rule=Host(`n8n.seudominio.com.br`)
         - traefik.http.routers.n8n_editor.entrypoints=websecure
         - traefik.http.routers.n8n_editor.priority=1
         - traefik.http.routers.n8n_editor.tls.certresolver=letsencryptresolver
         - traefik.http.routers.n8n_editor.tls=true
         - traefik.http.routers.n8n_editor.service=n8n_editor
         - traefik.http.services.n8n_editor.loadbalancer.server.port=5678
         - traefik.http.services.n8n_editor.loadbalancer.passHostHeader=true

networks:
  network_public:
    name: network_public
    external: true

