version: "3.8"

# mais info: https://youtu.be/tQ6-A1wl-C0
services:
  postgres:
    image: postgres:16.3-alpine3.19
    command: [postgres, --max_connections=100]
    networks:
      - postgres_network
    environment:
      POSTGRES_PASSWORD: UltraSecretPassWord
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
#      mode: replicated
#      replicas: 1
#      placement:
#         constraints: [ node.role == manager ]
      resources:
        limits:
          cpus: "0.55"
          memory: 420M

volumes:
  postgres_data:
    external: true

networks:
  postgres_network:
    external: true

