# mais info: https://youtu.be/tQ6-A1wl-C0
services:
  postgres:
    image: postgres:16.3-alpine3.19
    command: [postgres, --max_connections=100]
    restart: unless-stopped
    networks:
      - postgres_network
    environment:
      - POSTGRES_PASSWORD=4xtcEDGKVXl8LljsxcpWdO7nfydrnw5p
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo      
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    deploy:
#      mode: replicated
#      replicas: 1
#      placement:
#         constraints: [ node.role == manager ]
      resources:
        limits:
          cpus: "0.55"
          memory: 420M

volumes:
  postgres_storage:
    external: true

networks:
  postgres_network:
    external: true

